const selector= require('../supporting/selectors')
const data = require('../supporting/data')

module.exports = {
    runThrough1: browser => {
        browser
            .click(selectors.buttons.homeBtn)
            .waitForElementVisible(selectors.pageHeaders.promptTextOne, 200)
            .click(`${selectors.dropDown.loanDropDown} ${selectors.dropDown.purchase}`)
            .click(`${selectors.dropDown.propertyDropDown} ${selectors.dropDown.singleFamily}`)
            .click(selectors.buttons.nextBtn)
            .waitForElementVisible(selectors.pageHeaders.promptText, 200)
            .setValue(selectors.fields.cityInput, data.test1.purchaseCity)
            .click(selectors.buttons.nextBtn)
            .waitForElementVisible(selectors.pageHeaders.promptText, 200)
            .click(selectors.buttons.primaryBtn)
            .waitForElementVisible(selectors.pageHeaders.promptText, 200)
            .click(selectors.buttons.yesBtn)
            .waitForElementVisible(selectors.pageHeaders.promptText, 200)
            .click(selectors.buttons.yesBtn)
            .waitForElementVisible(selectors.pageHeaders.promptTextOne, 200)
            .setValue(selectors.fields.priceInput, data.test1.purchasePrice)
            .setValue(selectors.fields.downInput, data.test1.downPayment)
            .click(selectors.buttons.nextBtn)
            .waitForElementVisible(selectors.pageHeaders.promptText, 200)
            .click(selectors.buttons.excellentBtn)
            .waitForElementVisible(selectors.pageHeaders.promptText, 200)
            .click(selectors.buttons.noBankruptcyBtn)
            .waitForElementVisible(selectors.pageHeaders.promptText, 200)
            .setValue(selectors.fields.addressOne, data.test1.address1)
            .setValue(selectors.fields.addressTwo, data.test1.address2)
            .setValue(selectors.fields.addressThree, data.test1.address3)
            .click(selectors.buttons.nextBtn)
            .waitForElementVisible(selectors.pageHeaders.promptText, 200)
            .setValue(selectors.fields.firstName, data.test1.firstName)
            .setValue(selectors.fields.lastName, data.test1.lastName)
            .setValue(selectors.fields.email, data.test1.email)
            .click(selectors.buttons.nextBtn)
            .waitForElementVisible(selectors.summary.name, 200)
            browser.expect.element(selectors.summary.name).text.to.equal(data.test1.fullName)
            browser.expect.element(selectors.summary.email).text.to.equal(data.test1.email)
            browser.expect.element(selectors.summary.loanType).text.to.equal(data.test1.loan)
            browser.expect.element(selectors.summary.propertyType).text.to.equal(data.test1.propertyType)
            browser.expect.element(selectors.summary.propertyLocation).text.to.equal(data.test1.purchaseCity)
            browser.expect.element(selectors.summary.purchaseReason).text.to.equal(data.test1.purchaseReason)
            browser.expect.element(selectors.summary.propertyAlreadyLocated).text.to.equal(data.test1.propertyLocated)
            browser.expect.element(selectors.summary.agentAlreadyEngaged).text.to.equal(data.test1.agent)
            browser.expect.element(selectors.summary.price).text.to.equal(data.test1.purchasePrice)
            browser.expect.element(selectors.summary.downPayment).text.to.equal(data.test1.downPayment)
            browser.expect.element(selectors.summary.creditScore).text.to.equal(data.test1.creditScore)
            browser.expect.element(selectors.summary.creditHistory).text.to.equal(data.test1.creditHistory)
            browser.expect.element(selectors.summary.address1).text.to.equal(data.test1.address1)
            browser.expect.element(selectors.summary.address2).text.to.equal(data.test1.address2)
            browser.expect.element(selectors.summary.address3).text.to.equal(data.test1.address3)
            browser.click(selectors.buttons.sendBtn)
            .waitForElementVisible(selectors.pageHeaders.promptText, 200)
            browser.expect.element(selectors.pageHeaders.promptText).text.to.contain('Thank you for choosing Home Loan Wizard, a representative will be in touch with you shortly to talk about further steps.')
    }
}